version: '3.8'
services:
  postgres:
    image: postgres:15
    container_name: postgres_jpa_ex3
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: bd_jpa_ex3
    ports:
      - "5432:5432"
    volumes:
      - postgres-data-ex3:/var/lib/postgresql/data
volumes:
  postgres-data-ex3: